---
title: "Date_visualization"
author: "Katherine"
date: "2/4/2020"
output: html_document
---

```{r library}
library(tidyverse)
library(glmnet)
```

Read Dataset
```{r read dataset}
potatorar = read.csv("potatometadata_forClaudia.csv")

exploratory = potatorar[which(potatorar$Experiment == 2015), ]
confirmatory  = potatorar[which(potatorar$Experiment == 2017), ]
```

1. High nutrients and low nutrients
(I assume that fertilized means high nutrients??)
```{r}
p1 = ggplot(data=exploratory, aes(x=FieldID, y=Mean.Control.Microbe)) +
  geom_bar(stat="identity") +
  ylim(0,400) + 
  ggtitle("Exploratory Field & High")

p2 = ggplot(data=confirmatory, aes(x=FieldID, y=Mean.Control.Microbe)) +
  geom_bar(stat="identity") +
  ylim(0,400) + 
  ggtitle("Confirmatory Field & High")

p3 = ggplot(data=exploratory, aes(x=FieldID, y=Mean.LowN.Microbe)) +
  geom_bar(stat="identity") +
  ylim(0,400) + 
  ggtitle("Exploratory Field & Low")

p4 = ggplot(data=confirmatory, aes(x=FieldID, y=Mean.LowN.Microbe)) +
  geom_bar(stat="identity") +
  ylim(0,400) + 
  ggtitle("Confirmatory Field & Low")

grid.arrange(p1, p2, p3, p4, nrow = 2, ncol = 2)
```

2. diseases
```{r}
p5 = ggplot(data=exploratory, aes(x=FieldID, y=diffCSscore)) +
  geom_bar(fill="#DD8888",stat="identity") +
  ggtitle("Exploratory Field & disease severity")

p6 = ggplot(data=confirmatory, aes(x=FieldID, y=diffCSscore)) +
  geom_bar(fill="#6BBEEE",stat="identity") +
  ggtitle("Confirmatory Field & disease severity")
grid.arrange(p5, p6, nrow = 1, ncol = 2)
```

3.
```{r}
claderich_e = exploratory[, grep("claderich",colnames(potatorar))]
claderich_e=cbind(exploratory$FieldID,claderich_e)

claderich_c = confirmatory[, grep("claderich",colnames(potatorar))]
claderich_c=cbind(confirmatory$FieldID,claderich_c)

cladediv_e = exploratory[, grep("cladediv",colnames(potatorar))]
cladediv_e=cbind(exploratory$FieldID,cladediv_e)

cladediv_c = confirmatory[, grep("cladediv",colnames(potatorar))]
cladediv_c=cbind(confirmatory$FieldID,cladediv_c)
```

```{r}
 ggplot(data = claderich_e, fill = claderich_e0.1) +
  geom_point(aes(x = exploratory$FieldID, y=claderich0.1)) +
  geom_point(aes(x = exploratory$FieldID, y=claderich0.15 )) +
    geom_point(aes(x = exploratory$FieldID, y=claderich0.2)) +
    geom_point(aes(x = exploratory$FieldID, y=claderich0.25)) +
    geom_point(aes(x = exploratory$FieldID, y=claderich0.3)) +
    geom_point(aes(x = exploratory$FieldID, y=claderich0.35)) +
    geom_point(aes(x = exploratory$FieldID, y=claderich0.4)) +
    geom_point(aes(x = exploratory$FieldID, y=claderich0.45)) +
    geom_point(aes(x = exploratory$FieldID, y=claderich0.5)) +
    geom_point(aes(x = exploratory$FieldID, y=claderich0.55 )) +
    geom_point(aes(x = exploratory$FieldID, y=claderich0.6)) +
    geom_point(aes(x = exploratory$FieldID, y=claderich0.7)) +
    geom_point(aes(x = exploratory$FieldID, y=claderich0.8)) +
    ylab("claderich")+
    xlab("Fields")
  
```

Rearranging the tables
```{r}
nu = data.frame("nutrients" = c("high", "low"))
nu = data.frame("nutrients" = nu[rep(seq_len(nrow(nu)), each = 13), ])
t1 =  potatorar[, -which(colnames(potatorar)=="Mean.LowN.Microbe")]
t2 =  potatorar[, -which(colnames(potatorar)=="Mean.Control.Microbe")]

t3 =  t1[, -which(colnames(t1)=="varNtub")]
t4 =  t2[, -which(colnames(t2)=="varCtub")]

t5 = t3[, -which(colnames(t3)=="Std.Err.Mean.LowN.Microbe")]  
t6 =  t4[, -which(colnames(t4)=="Std.Err.Mean.Control.Microbe")]

t7 = t5[, -which(colnames(t5)=="invVar_Ntub")]  
t8 =  t6[, -which(colnames(t6)=="invVar_Ctub")]

c1 =  cbind(t7,data.frame("nutrients" = nu[1:13,]))
names(c1)[names(c1) == "Mean.Control.Microbe"] <- "yields_average"
names(c1)[names(c1) == "varCtub"] <- "yields_variance"
names(c1)[names(c1) == "Std.Err.Mean.Control.Microbe"] <- "yields_std.err.mean"
names(c1)[names(c1) == "invVar_Ctub"] <- "yields_inverse.var"

c2 = cbind(t8,data.frame("nutrients" = nu[14:26,]))
names(c2)[names(c2) == "Mean.LowN.Microbe"] <- "yields_average"
names(c2)[names(c2) == "varNtub"] <- "yields_variance"
names(c2)[names(c2) == "Std.Err.Mean.LowN.Microbe"] <- "yields_std.err.mean"
names(c2)[names(c2) == "invVar_Ntub"] <- "yields_inverse.var"

potatorar_update = rbind(c1, c2)
potatorar_update = potatorar_update %>% arrange(potatorar_update$FieldID)
write.csv(potatorar_update, file = "potatorar_update.csv", quote = FALSE)
```


